import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{SITE_CONFIG as C}from'../shared/config';
import{copyIP}from'../shared/copy';
import{MCButton,MCLink}from'../shared/Minecraft';
import'./style.css';
type Step='desktop'|'launching'|'menu'|'servers'|'direct'|'add'|'saved'|'selected'|'connecting'|'done';
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function Hint({children}:{children:React.ReactNode}){return <div className="tutorial-hint">{children}<i/></div>}
function Desktop({go}:{go:()=>void}){const launcherIcon=new URL('../assets/minecraft_favicon.png',import.meta.url).href;return <div className="desktop"><Hint>Откройте Minecraft Launcher</Hint><div className="desk-icons"><button className="desk-icon"><span>💻</span>Этот компьютер</button><button className="desk-icon"><span>🗑️</span>Корзина</button><button className="desk-icon target" onDoubleClick={go} onClick={go}><img src={launcherIcon} alt="Minecraft Launcher"/>Minecraft Launcher</button><button className="desk-icon"><span>🌐</span>Microsoft Edge</button></div><div className="taskbar"><span>⊞</span><span>⌕</span><span>📁</span><span>🌐</span><img src={launcherIcon} alt="Minecraft Launcher"/><time>{new Date().toLocaleTimeString('ru',{hour:'2-digit',minute:'2-digit'})}</time></div></div>}
function Screen({children,menu=false}:{children:React.ReactNode;menu?:boolean}){return <div className={`game ${menu?'main-menu':''}`}><div className="game-blur"/><div className="game-content">{children}</div>{menu&&<><span className="version">Minecraft {C.server.version}</span><span className="copyright">Copyright Mojang AB. Do not distribute!</span></>}</div>}
function MainMenu({next}:{next:()=>void}){return <Screen menu><div className="minecraft-logo"><img src={new URL('../assets/Minecraft_Java_Edition.png',import.meta.url).href} alt="Minecraft Java Edition"/><em>That's Numberwang!</em></div><Hint>Нажмите Multiplayer</Hint><div className="main-buttons"><MCButton>Singleplayer</MCButton><MCButton onClick={next}>Multiplayer</MCButton><MCButton>Minecraft Realms</MCButton><div className="menu-footer"><MCButton className="square">🌐</MCButton><MCButton>Options...</MCButton><MCButton>Quit Game</MCButton><MCButton className="square">♙</MCButton></div></div></Screen>}
function MultiplayerButtons({join,direct,add,back,enabled=true}:{join?:()=>void;direct:()=>void;add?:()=>void;back:()=>void;enabled?:boolean}){return <div className="multiplayer-buttons"><div><MCButton disabled={!enabled} onClick={join}>Join Server</MCButton><MCButton onClick={direct}>Direct Connection</MCButton><MCButton onClick={add}>Add Server</MCButton></div><div><MCButton>Edit</MCButton><MCButton>Delete</MCButton><MCButton>Refresh</MCButton><MCButton onClick={back}>Back</MCButton></div></div>}
function ServerEntry({selected,onSelect}:{selected:boolean;onSelect:()=>void}){return <button className={`server-entry ${selected?'chosen':''}`} onClick={onSelect}><img className="server-icon" src={new URL('../assets/server_icon.png',import.meta.url).href} alt="GTAMINE"/><span className="server-copy"><b>{C.server.name}</b><span className="motd"><strong>GTAMINE</strong><br/>Город <b>Над-Сити</b> ждёт тебя!</span></span><span className="players">1 / 1000<img src={new URL('../assets/ping.png',import.meta.url).href} alt="Отличное соединение"/></span></button>}
function Joined({copied,copy}:{copied:boolean;copy:()=>void}){return <div className="joined"><video className="joined-video" src={new URL('../assets/join.mp4',import.meta.url).href} autoPlay muted playsInline onEnded={e=>e.currentTarget.pause()}/><div className="joined-shade"/><section className="joined-modal" role="dialog" aria-modal="true" aria-labelledby="joined-title"><h1 id="joined-title">Вы зашли на сервер!</h1><p>Вам остаётся только зарегистрироваться.<br/>И вообще — чего вы ждёте?</p><button className="joined-ip" onClick={copy}>IP: <strong>{C.server.host}</strong><small>{copied?'IP скопирован':'Нажмите, чтобы скопировать'}</small></button><div className="joined-actions"><MCLink href={C.downloads.windows} target="_blank" rel="noopener noreferrer">Скачать игру на ПК</MCLink><MCLink href={C.downloads.android} target="_blank" rel="noopener noreferrer">Скачать на Android</MCLink><MCLink href="../ios/">Скачать на iOS</MCLink></div></section></div>}
function Tutorial(){const[step,setStep]=useState<Step>('desktop');const[address,setAddress]=useState('');const[copied,setCopied]=useState(false);const[status,setStatus]=useState('Connecting to the server...');const valid=[C.server.host,`${C.server.host}:${C.server.port}`].includes(address.trim());
const launch=async()=>{setStep('launching');await wait(1450);setStep('menu')};const connect=async()=>{setStatus('Connecting to the server...');setStep('connecting');for(const s of['Connecting to the server...','Logging in...','Joining world...']){setStatus(s);await wait(1000)}await wait(400);setStep('done')};const copy=async()=>{await copyIP(C.server.host);setCopied(true);setTimeout(()=>setCopied(false),1800)};useEffect(()=>{document.title=`${C.server.name} — туториал`},[]);
if(step==='desktop')return <Desktop go={launch}/>;if(step==='launching')return <div className="mojang-loading"><img className="mojang-logo" src={new URL('../assets/mojang.png',import.meta.url).href} alt="Mojang Studios"/><div className="loading-bar"><i/></div></div>;if(step==='menu')return <MainMenu next={()=>setStep('servers')}/>;
if(step==='servers')return <Screen><h1 className="screen-title">Play Multiplayer</h1><Hint>Добавьте GTAMINE в список серверов</Hint><div className="server-space"><p>Scanning for games on your local network</p><small>o o o</small></div><MultiplayerButtons enabled={false} direct={()=>{setAddress(C.server.host);setStep('direct')}} add={()=>setStep('add')} back={()=>setStep('menu')}/></Screen>;
if(step==='direct')return <Screen><h1 className="screen-title">Direct Connection</h1><Hint>Адрес сервера уже заполнен</Hint><div className="direct-form"><label>Server Address<input autoFocus value={address} onChange={e=>setAddress(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&address.trim())void connect()}}/></label><div className="direct-actions"><MCButton disabled={!address.trim()} className={address.trim()?'target':''} onClick={connect}>Join Server</MCButton><MCButton onClick={()=>setStep('servers')}>Cancel</MCButton></div></div></Screen>;
if(step==='add')return <Screen><h1 className="screen-title">Add Server</h1><Hint>{valid?'Сохраните сервер':'Введите адрес сервера'}</Hint><div className="edit-form"><label>Server Name<input value={C.server.name} readOnly/></label><label>Server Address<input autoFocus value={address} onChange={e=>setAddress(e.target.value)}/></label><button className="copy-ip" onClick={copy}>{C.server.host}<small>{copied?'IP скопирован':'нажмите, чтобы скопировать'}</small></button><MCButton>Server Resource Packs: Prompt</MCButton><div className="edit-actions"><MCButton disabled={!valid} className={valid?'target':''} onClick={()=>setStep('saved')}>Done</MCButton><MCButton onClick={()=>setStep('servers')}>Cancel</MCButton></div></div></Screen>;
if(step==='saved'||step==='selected')return <Screen><h1 className="screen-title">Play Multiplayer</h1><Hint>{step==='saved'?'Выберите GTAMINE':'Нажмите Join Server'}</Hint><div className="server-space populated"><ServerEntry selected={step==='selected'} onSelect={()=>setStep('selected')}/><p>Scanning for games on your local network</p><small>o o o</small></div><MultiplayerButtons enabled={step==='selected'} join={connect} direct={()=>{setAddress(C.server.host);setStep('direct')}} add={()=>setStep('add')} back={()=>setStep('menu')}/></Screen>;
if(step==='connecting')return <div className="connecting-stage"><Screen><div className="connect"><h2>{status}</h2><MCButton onClick={()=>setStep('selected')}>Cancel</MCButton></div></Screen><div className="connection-fade"/></div>;
return <Joined copied={copied} copy={copy}/>}
createRoot(document.getElementById('root')!).render(<Tutorial/>);
